[tool.poetry]
name = "leet-codes"
version = "0.1.0"
description = "Practicing leet-codes"
authors = ["Bushan Bengaluru"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
